version: "3.7"
services:
    covid19_tracker:
        container_name: covid19_tracker
        image: test/covid19_tracker:latest
        build: .
        restart: always
        ports:
            - 5000:5000
